soc: rockchip: pm_config: ROCKCHIP_SUSPEND_MODE depends on SUSPEND
Fixes the following warning when !SUSPEND:
drivers/soc/rockchip/rockchip_pm_config.c:258:34: error: use of undeclared identifier 'mem_sleep_current'
drivers/soc/rockchip/rockchip_pm_config.c:551:34: error: use of undeclared identifier 'mem_sleep_current'

Change-Id: I9c6c215094444937d58fc877d8841669b54ee63d
Signed-off-by: Tao Huang <huangtao@rock-chips.com>